pom.xml, src/main/java/net/revelc/code/impsort/ImpSort.java, src/test/java/net/revelc/code/impsort/ImpSortTest.java, src/test/resources/UnusedImports.java
This change adds some code to the function that removes unused imports,
to ensure that imports referenced by Javadoc comments (such as {@link
SomeClass}) are not stripped out.
The unit test for removing imports is extended to test this new
functionality.
=> Don't remove imports referenced by Javadoc comments.

pom.xml, src/test/java/net/revelc/code/impsort/ImpSortTest.java, src/test/resources/EmptyJavadoc.java
Fixes #16 .
Tested with javaparser:3.15.4-SNAPSHOT. This PR is waiting for tonight release of javaparser:3.15.4
=> Fix #16: Fixed ArrayIndexOutOfBounds on class with empty javadoc

src/main/java/net/revelc/code/impsort/ImpSort.java
Look for used imports in JavadocBlockTag objects, which appear not to be
parsed correctly from the Javadoc comment block.
=> Fix #19 workaround for javaparser/javaparser#2408

.gitignore, src/main/java/net/revelc/code/impsort/Grouper.java, src/main/java/net/revelc/code/impsort/ImpSort.java, src/main/java/net/revelc/code/impsort/Import.java, src/main/java/net/revelc/code/impsort/LineEnding.java, src/main/java/net/revelc/code/impsort/Result.java, src/main/java/net/revelc/code/impsort/maven/plugin/AbstractImpSortMojo.java, src/test/java/net/revelc/code/impsort/ImpSortTest.java, src/test/java/net/revelc/code/impsort/LineEndingTest.java
=> Add configurable EOL specifier

src/main/java/net/revelc/code/impsort/ImpSort.java, src/main/java/net/revelc/code/impsort/Result.java, src/main/java/net/revelc/code/impsort/ex/ImpSortException.java, src/test/java/net/revelc/code/impsort/LineEndingEdgeCasesTest.java
* Return an empty result if the file is empty to skip the file
* Only throw an exception when line ending is unknown, if the line
ending configuration is set to KEEP
* When reading all lines from the buffer into a list, do not depend on
the previously detected line endings, and instead read all lines
as-is, regardless of line ending previously detected
=> Handle empty files and unknown line endings better

src/main/java/net/revelc/code/impsort/ImpSort.java, src/main/java/net/revelc/code/impsort/maven/plugin/AbstractImpSortMojo.java, src/test/java/net/revelc/code/impsort/maven/plugin/AbstractImpSortMojoTest.java
* Add a new mojo option to make the compiler compliance level
configurable
* Create a new ImpSort constructor to support providing the compiler
compliance level
* Ensure parseResult only shows problems appropriate to the specific
Java language source version, based on the configured compiler
compliance level
=> Make compiler compliance configurable

pom.xml, src/main/java/net/revelc/code/impsort/maven/plugin/AbstractImpSortMojo.java
* Update build plugins to latest
* Update dependencies to latest
* Lower output message for compiler compliance to debug
* Reduce output lines for sorting/checking to a single line
This fixes #40
=> Update plugins/dependencies and improve output

pom.xml, src/main/java/net/revelc/code/impsort/maven/plugin/AbstractImpSortMojo.java, src/test/java/net/revelc/code/impsort/ImpSortTest.java, src/test/java/net/revelc/code/impsort/maven/plugin/AbstractImpSortMojoTest.java, src/test/resources/Java13Preview.java
* Add a test case for Java 13 preview features, for #44 and #45
* Bump dependency and plugin versions
* Ensure reporting plugins for site build are properly versioned via the
pluginManagement section
* Make compliance option uppercase when comparing, so it gets the
correct LanguageLevel for `PREVIEW` versions from the javaparser
library
=> Add test case for preview features and bump deps

pom.xml
Fix issue identified in comment (overzealous record parsing)
https://github.com/revelc/impsort-maven-plugin/issues/44#issuecomment-840756202
=> Bump javaparser to 3.22.1

pom.xml
parent will never be up one root.  This is best practice.  While most won't see the issue, those like myself that have a pom one above for specific need will continually get warnings that the project is misconfigured.
=> [pom] Add empty relativePath to force parent check in .m2

pom.xml, src/test/java/net/revelc/code/impsort/ImpSortTest.java, src/test/java/net/revelc/code/impsort/LineEndingEdgeCasesTest.java, src/test/java/net/revelc/code/impsort/LineEndingTest.java, src/test/java/net/revelc/code/impsort/maven/plugin/AbstractImpSortMojoTest.java
The project currently uses the outdated JUnit 4.13.2. In order to make it easier to write tests and easier for future contributors to easily start working with the project, this path migrates the test suite to the modern JUnit Jupiter.
Changes:
- The `junit:junit:4.13.2` dependency was replaced with `org.junit.jupiter:junit-jupiter:5.8.1`.
- The `org.junit.jupiter.api.Test` annotation was used as a drop-in replacement for `org.junit.Test`.
- The static imports from `org.junit.jupiter.api.Assertions` were used as drop-in replacements for the static imports from `org.junit.Assert`.
- `LineEndingEdgeCasesTest` was rewritten to use JUnit Jupiter's `org.junit.jupiter.api.io.TempDir` annotation instead of JUnit 4's `org.junit.rules.TemporaryFolder`.
=> Migrate tests to modern JUnit Jupiter

pom.xml, src/main/java/net/revelc/code/impsort/Result.java
* Update parent POM version
* Remove redundant enforcer execution in favor of overriding parent
POM minimum Maven and Java versions in properties
* Update plugins to latest
* Fix spotbugs warning about returning internal mutable type in
Result.java
* Update guava, javaparser, and plexus-utils dependencies to latest
* Apply sortpom updates
=> Update plugin and dependency versions

pom.xml
This patch follows up on the review given for #51 and uses `maven-surefire-plugin`'s configuration to set the tempdir to target and
restore the behavior change introduced in that PR.
Note:
This fix will only effect running the test via maven. If the test is manually run (e.g., from an IDE), `java.io.tmpdir` should be overridden manually too.
=> Set surefire's tempdir to target

src/main/java/net/revelc/code/impsort/maven/plugin/AbstractImpSortMojo.java
to remove unnecessary disk path fixing #58 
Current usage ends up with caching showing full system path from root drive such as C drive.  That is unnecessary for the caching solution.  Change here to same logic used in formatter maven plugin so that it picks up from root of project only.
=> [cache] Change 'toAbsolutePath().normalize()' to 'toFile().getCanonicalPath()'

pom.xml
This fixes a bug when `sealed` is used in an attribute
- Fixes #72
Changelog: https://github.com/javaparser/javaparser/releases/tag/javaparser-parent-3.25.4
=> Bump java-parser to 3.25.4

src/site/markdown/index.md.vm
Also added the `removeUnused` parameter in the example configuration because it's likely a popular one.
=> Expand documentation with list of supported parameters

pom.xml
Over on javaparser, noticed this ticket https://github.com/javaparser/javaparser/issues/3309.
This indicated this did not work with maven plugins but we are one, so I tried to check help.  Noticed we had plugin management and m2e data for same but failed to do this at all.  Added it and have tested it, works as expected.  Don't recall if some reason it was not here but its generally best practice to offer 'help' at very least.
=> [pom] Add default descriptor / helpmojo

pom.xml, src/main/java/net/revelc/code/impsort/ImpSort.java, src/main/java/net/revelc/code/impsort/ParseProblemFilter.java, src/main/java/net/revelc/code/impsort/Result.java, src/main/java/net/revelc/code/impsort/maven/plugin/AbstractImpSortMojo.java, src/test/java/net/revelc/code/impsort/ImpSortTest.java, src/test/java/net/revelc/code/impsort/maven/plugin/AbstractImpSortMojoTest.java, src/test/resources/Java21RecordDeconstruction.java
- unfortunately the used https://github.com/javaparser/javaparser is stuck with Java 18 (in latest version 3.25.7)
- but it turned out that even in case of a parse error somewhere in a top level declaration the imports are correctly parsed and available
- introduced `<ignoreIrrelevantParseErrors>` which is `false` for now but allows to ignore the parse errors in the top level declarations (they shouldn't affect import sorting at all)
- introduced a test case with Java 21 record deconstruction
=> ignore parse errors below imports (to allow the plugin to work with Java > 18)

.github/workflows/maven.yaml
- Allow any branch to build as it is not on us to enforce downstream repo usage.  Has zero effect on this repo.
- Make sure we test latest LTS release of java and last LTS.
- Use githubs built in caching for maven
=> [GHA] Rework github actions

.github/dependabot.yml, pom.xml
* Bump parent POM to revelc-6
* Workaround license plugin not able to read Iso8859File.java
* Add dependency convergence check
* Drop unused plexus-xml
* Follow version property naming convention from parent POM
=> Update to latest parent POM

src/main/java/net/revelc/code/impsort/maven/plugin/AbstractImpSortMojo.java
Support `RAW`, `POPULAR`, `CURRENT`, and `BLEEDING_EDGE` as valid Java language level compliance options.
This fixes #135
=> Add more compliance options
